"""empty message

Revision ID: c54c55b9e24a
Revises: cb84a780a598
Create Date: 2025-01-14 18:20:26.349355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54c55b9e24a'
down_revision = 'cb84a780a598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_personal', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('nombre_restaurante', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('codigo_admin', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['telefono'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo_admin')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')
        batch_op.drop_column('nombre_restaurante')
        batch_op.drop_column('username')
        batch_op.drop_column('nombre_personal')

    # ### end Alembic commands ###
